replicaCount: 1

image:
  repository: rick-and-morty-api
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: ""
      paths:
        - path: /api
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi